#!/bin/bash

echo "***TEST 10***"
echo "***Various errors***." 

rm *.json
rm *.jar*
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "****************************************************************************"
echo "URLENCODE the identifier"
IpIdUrl=$(urlencode $IpId)
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : Using PUT instead of GE******************************************"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
cmd="curl -i -X PUT $GaUrl/oaisif/v1/sources -H accept:application/json"
echo "***executing***" "$cmd"
echo "***SHOULD GET 405 error Method Not Allowed	The HTTP method (GET, POST, PUT, DELETE) isn't supported for this URL."
echo $cmd | bash
echo "****************************************************************************"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : Try to get non-existent propert**********************************"
cmd="curl -i -X GET $GaUrl/oaisif/v1/sources/JUNK -H accept:application/json"  
echo "***executing***" "$cmd"
echo "***SHOULD GET 404 error Not Found	The server can't find the requested resource."
echo $cmd | bash
echo "****************************************************************************"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : try to get non-existent IP ID************************************"
cmd="curl -i -X GET $GaUrl/oaisif/v1/information-packages/9999 -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error Not Found	The server can't find the requested resource."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : try to get non-existent component of IP**************************"
cmd="curl -i -X GET $GaUrl/oaisif/v1/information-packages/$IpIdUrl/XO -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error Not Found The server can't find the requested resource."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : trying non-existent REST end point*******************************"
cmd="curl -i -X GET $GaUrl/oaisif/v1/information/9999 -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error Not Found	The server can't find the requested resource."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : trying non-existent package ID***********************************"
cmd="curl -i -X GET $SaUrl/oaisif/v1/specific-adapter/information-packages/9999 -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error"
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : trying to PUT instead of GET**************************************"
cmd="curl -i -X PUT $GaUrl/oaisif/v1/information-packages -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 405 error Method Not Allowed	The HTTP method (GET, POST, PUT, DELETE) isn't supported for this URL."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : trying to get non-existent propert*******************************"
cmd="curl -i -X GET $GaUrl/oaisif/v1/properties/JUNK -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error Not Found	The server can't find the requested resource."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : asking Switchboard for non-existent repository*******************"
cmd="curl -i -X GET $SbUrl/oaisif/v1/switchboard/9999 -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error Not Found	The server can't find the requested resource."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "***ERROR : trying to get non-existent RepInfo*******************************"
cmd="curl -i -X GET $RroriUrl/oaisif/v1/representation-info-repository/information-packages/JUNK -H accept:application/json"
echo "****************************************************************************"
echo "***executing***" "$cmd"
echo "****************************************************************************"
echo "***SHOULD GET 404 error Not Found The server can't find the requested resource."
echo $cmd | bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
